language: node_js
sudo: required
node_js: 12.22.1
cache: npm
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
